services:
  project:
    container_name: project
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    command: ['python3', '-m', 'src.project.main']
    # command: ["uvicorn", "src.project.main:app", "--host", "0.0.0.0", "--port", "8000"]
    healthcheck:
      test: ["CMD", "curl", "http://localhost:8000/healthcheck/alive"]
      interval: 5s
      timeout: 30s
      retries: 5
    networks:
      - monitoring

  alloy:
    container_name: alloy
    image: grafana/alloy:v1.13.2
    ports:
      - 12345:12345
    volumes:
      - ./infrastructure/alloy/config.alloy:/etc/alloy/config.alloy
      - /var/run/docker.sock:/var/run/docker.sock
    command:
      - run
      - --server.http.listen-addr=0.0.0.0:12345
      - --storage.path=/var/lib/alloy/data
      - /etc/alloy/config.alloy
    depends_on:
      project:
        condition: service_healthy
    networks:
      - monitoring

  prometheus:
    container_name: prometheus
    image: prom/prometheus:v3.3.1
    command: 
      - "--web.enable-remote-write-receiver"
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - 9090:9090
    networks:
      - monitoring

  loki:
    container_name: loki
    image: grafana/loki:3.6.3
    command: 
      - "-config.file=/etc/loki/local-config.yaml"
    ports:
      - 3100:3100
    networks:
      - monitoring

  grafana:
    container_name: grafana
    image: grafana/grafana:12.0.0
    ports:
      - 3000:3000
    volumes:
      - ./infrastructure/grafana/dashboard/dada.json:/etc/grafana/provisioning/dashboards/json/dada.json
      - ./infrastructure/grafana/dashboard-provider.yaml:/etc/grafana/provisioning/dashboards/dashboard-provider.yaml
      - ./infrastructure/grafana/datasource/loki.yaml:/etc/grafana/provisioning/datasources/loki.yaml
      - ./infrastructure/grafana/datasource/prometheus.yaml:/etc/grafana/provisioning/datasources/prometheus.yaml
    depends_on:
      project:
        condition: service_healthy
    networks:
      - monitoring

networks:
  monitoring:
    driver: "bridge"
