services:
  redis:
    container_name: redis
    image: redis:8.0-M02-bookworm
    env_file:
      - .env
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 3

  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    env_file:
      - .env
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "db_prod" ]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
    depends_on:
      redis:
        condition: service_healthy

  minio-s3:
    restart: always
    image: minio/minio:RELEASE.2024-07-31T05-46-26Z
    container_name: minio-s3
    ports:
      - ${MINIO_API_PORT}:${MINIO_API_PORT}
      - ${MINIO_WEB_UI_PORT}:${MINIO_WEB_UI_PORT}
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ':${MINIO_WEB_UI_PORT}' --address ':${MINIO_API_PORT}'
    # volumes:
    #   - ./minio_data:/data
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${MINIO_API_PORT}/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - pp-net

  s3_setup:
    image: minio/mc:RELEASE.2024-08-13T05-33-17Z
    container_name: s3_setup
    depends_on:
      - minio-s3
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    entrypoint: ["/bin/sh", "-c"]
    env_file:
      - .env
    command:
      - |
        mc alias set myminio http://minio-s3:${MINIO_API_PORT} ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD}
        mc admin user svcacct add --access-key ${MINIO_AWS_ACCESS_KEY_ID} --secret-key ${MINIO_AWS_SECRET_ACCESS_KEY} myminio ${MINIO_ROOT_USER}
        mc mb myminio/${MINIO_BUCKET_NAME}
    networks:
      - pp-net

