global:
  scrape_interval: 5s
  evaluation_interval: 5s 

scrape_configs:
  - job_name: 'project'
    metrics_path: '/metrics'
    scrape_interval: 5s
    static_configs:
      - targets: ['project:8000']
